from_start = '//span/a[contains(@href,"/refactoring/what-is-refactoring")]'
dirty_code = '//span/a[contains(@href,"/refactoring/technical-debt")]'
how_to = '//span/a[contains(@href,"/refactoring/how-to")]'
ru_language = '//div[@class="nano-content"]/div/a[contains(@href,"https://refactoring.guru/ru")]'
ua_language = '//div[@class="nano-content"]/div/a[contains(@href,"https://refactoring.guru/uk")]'
ch_lang = '//span[@class="d-none d-lg-inline"][contains(text(), "中文")]'
por_lang = '//span[@class="d-none d-lg-inline"][contains(text(), "Português-Br")]'
